version: '3.8'

services:
  streamlit:
    build: ./streamlit-tips-app
    ports:
      - "8501:8501"
    networks:
      - myNetTask01
    restart: unless-stopped

  telebot:
    build: ./telegram_fio_translit_bot
    env_file:
      - .env
    volumes:
      - ./telegram_fio_translit_bot/log:/app/log
    networks:
      - myNetTask01
    restart: unless-stopped

networks:
  myNetTask01:
    name: myNetTask01